### ISSUE TITLE
Can't set embedded property from existing instance

### ISSUE THREAD

**Issue by jameskleeh** [grails/gorm-mongodb#27]
Added a failing test with the PR https://github.com/grails/gorm-mongodb/pull/26

**Comment by puneetbehl** [comment]
This is happening because `Address` is a domain class and when you create a new `Address` object and assign it to the parent class `Individual` object then the properties of the `Address` are not dirty and the below code: 

```groovy
def i = Individual.first()
i.address = Address.findByPostCode("44512") // i.address.isDirty() == false 
```

In `PersistentEntityCodec.groovy` returns an empty list of dirty properties for the address (embedded child object).

[`def dirtyProperties = new ArrayList<String>(dirty.listDirtyPropertyNames())`](https://github.com/grails/gorm-mongodb/blob/master/grails-datastore-gorm-mongodb/src/main/groovy/org/grails/datastore/mapping/mongo/engine/codecs/PersistentEntityCodec.groovy#L219)

So, I believe there are two solutions:

**a.** Make sure`Address.groovy` the class is not an Entity class when you are embedding it to the `Individual.groovy`.

**b.** Explicitly mark the address object dirty by calling `markDirty()` method as follows:
```groovy
void "Test overwrite an embedded property with a previously saved instance"() {
    given:"A domain with an embedded association"
    def address = new Address(postCode: "30483")
    new Address(postCode: "44512").save(flush: true)
    def i = new Individual(name:"Bob", address: address)
    i.save(flush:true)
    session.clear()

    when:
    i = Individual.first()
    i.address = Address.findByPostCode("44512")
    i.address.markDirty()
    i.save(flush:true)
    session.clear()

    and:"We query to get the embedded instance"
    i = Individual.first()

    then: "the result is correct"
    i.address.postCode == "44512"
}
```
