### ISSUE TITLE
RxGorm + Vertx = No dynamic finders, proper where clauses or 1:1 child mapping

### ISSUE THREAD

**Issue by mvniekerk** [grails/gorm-mongodb#42]
Git repo with tests showing failures:
https://github.com/mvniekerk/vertxgormfail

**Comment by graemerocher** [comment]
The dynamic finders are not working because you have not annotated your domain classes with `grails.gorm.annotations.Entity`

The where method is not working in one case because `where` methods do not work within spock `expect` or `then` blocks generally due to a conflict in the transformations, if you move those `where` declaration outside of Spock's `expect` block they work. This is a general limitation that exists with regular GORM too.

The 1:1 issue is because your `Role` class is returning different hash codes for the proxies hence the failures.

**Comment by mvniekerk** [comment]
Thank you @graemerocher 

I did follow the "RxGorm for Java" page - 
From above I take it the RxMongoEntity is not the only needed trait to implement as below:

https://goo.gl/photos/dUasecrZcUngo7jY6

Thus an update on the docs side is needed. Thanks again for the assistance.
