### ISSUE TITLE
isDirty/hasChanged always returns true for properties of other domain type

### ISSUE THREAD

**Issue by snimavat** [grails/gorm-mongodb#48]
There seems to be actually two issues:

In integration tests:
hasChanged/isDirty always seem to return true for every property

In running app
hasChanged/isDirty works for regular properties
but for property of type other domains, hasChaned will return true even if the referenced domain has not changed

See attached sample, it has a DirtyPropertiesSpec which fails

[contentful-bug-report-30062017.zip](https://github.com/grails/gorm-mongodb/files/1115696/contentful-bug-report-30062017.zip)

In our app, after the databinding (which has parameter "parent.id" = xxx) 
if i check, hasChanged("parent") it returns true, even if the parent object is same

This thing works fine with hibernate, if u remove the `static mapWith = "mongo" ` from domain, and run the test again, it will pass the isDirty() checks, but not hasChanged() checks

**Comment by snimavat** [comment]
Alright, implementing hasCode/equals has fixed the problem with run-app
But definitely some thing is wrong with the integration tests. hasChanged/isDirty always returns true unless we actually save with flush

**Comment by puneetbehl** [comment]
I think the way `hasChanged` or `isDirty` work is that they track changes in the object state as compared to the state in the database. And in case of integration tests, the changes are not flushed till the end so that might be the reason you are  seeing this behaviour without `flush: true`.

Also, I am not able to build the ZIP attached as `gradle.properties` file is missing. Please specify Grails and GORM version whenever you create an issue.

**Comment by puneetbehl** [comment]
FYI, you could look into some sample tests [here](https://github.com/grails/gorm-mongodb/blob/master/grails-datastore-gorm-mongodb/src/test/groovy/org/grails/datastore/gorm/mongo/SimpleHasManySpec.groovy#L47)

**Comment by puneetbehl** [comment]
Closed due to lack of feedback.
