### ISSUE TITLE
Changes to items in hasMany collection not persisted

### ISSUE THREAD

**Issue by paulfairless** [grails/gorm-mongodb#59]
I have been refactoring a domain from using an embedded collection into separate collections and encountered an issue with cascading saves. Changes to the child collection are not persisted upon saving the parent domain object. I've tried using `markDirty` with no success. The following code recreates the issue. It passes when using an H2 datasource or with an embedded collection.

Grails 3.1.16
gorm-mongo with both 5.0.8 and 6.1.2

Order.groovy
```
class Order {
    ObjectId id
    int orderNumber
    static hasMany = [items: OrderItem]
}
```

OrderItem.groovy
```
class OrderItem {
    ObjectId id
    String description
    static belongsTo = Order
}
```

Bootstrap.groovy
```
class BootStrap {

    def init = { servletContext ->
        int orderNumber = new Random().nextInt()
        Order order = new Order(orderNumber: orderNumber)
        order.addToItems(new OrderItem(description: 'a product'))
        order.save(flush:true)

        Order.withNewSession {
            order = Order.findByOrderNumber(orderNumber)
            order.items.first().description = 'an updated product'
            order.markDirty('items')
            order.save(flush:true)
        }

        Order.withNewSession {
            order = Order.findByOrderNumber(orderNumber)
            assert order.items.first().description == 'an updated product'
        }
    }
    def destroy = {
    }
}
```

**Comment by puneetbehl** [comment]
Try setting `order.items.markDirty()` and then try again.

**Comment by paulfairless** [comment]
I've tried using markDirty and it does not seem to help in this case.

**Comment by puneetbehl** [comment]
I would request you to please share a sample application.

**Comment by puneetbehl** [comment]
FYI, I was able to resolve the issue by:
* Explicitly calling the `order.items.markDirty()` instead of `order.markDirty('items')`
* Wrapping saves inside `withNewTransaction`
* Creating a service as follows: 
    ```groovy
    @Transactional
    class OrderService {
   
        Order createNew(Integer orderNumber, String itemDescription) {
            Order order = new Order(orderNumber: orderNumber)
            order.addToItems(new OrderItem(description: itemDescription))
            order.save(flush: true)
        }
    
        Order updateItem(Order order, ObjectId itemId, String itemDescription) {
            order.with {
                OrderItem item = order.items.find {it.id == itemId}
                item.description = itemDescription
                save(flush: true)
            }
        }
    
        Order get(ObjectId id) {
            Order.get(id)
        }
    }
    ```

**Comment by paulfairless** [comment]
You can simply copy the domain and bootstrap above into a new project to recreate. Unless you need the full app?

**Comment by paulfairless** [comment]
I see, thank you! Out of interest what is the difference between the two methods? Just so I know when to use one over the other.

**Comment by puneetbehl** [comment]
Please find the [attached zip](https://github.com/grails/gorm-mongodb/files/1783883/issue59.zip) and run it.

For the difference, I think 
* Calling `order.markDirty()` executes `org.grails.datastore.mapping.dirty.checking.DirtyCheckable.markDirty(propertyName)` which works for the direct properties 
* For association such as many-to one, many-to many etc with`DBRefs` (not using embedded list or objects) we need to call `org.grails.datastore.mapping.dirty.checking.DirtyCheckableCollection.markDirty()` in order to mark save them with `Order` save which is execute when you call `order.items.markDirty()`.

Also, the writes should be done in the transaction using `withTransaction` or ideally using a transactional service as shown in the previous comment.  

Probably the behavior you are seeing is due to [this fix](https://github.com/grails/grails-data-mapping/issues/844). I would also suggest reading https://github.com/grails/grails-data-mapping/issues/865
