### ISSUE TITLE
RxGorm MongoDB

### ISSUE THREAD

**Issue by theiosdevguy** [grails/gorm-mongodb#97]
Hello Grails Team,

I believe with latest updates, RxGORM for MongoDB is being discontinued. Is that correct? Is there any specific reason for this? 

I have found the plugin very useful for handling Asynchronous tasks and doing DB operations in a separate thread. What would be the alternative that you suggest?

Thanks.

**Comment by puneetbehl** [comment]
Yes, due to lack of interest and usage from the community, the RxGORM module for MongoDB has been removed. You could create a new plugin to extend from the previous implementation and use [MongoDB Reactive Streams](http://mongodb.github.io/mongo-java-driver/4.0/driver-reactive/).

Please note that you could still use MongoDB Reactive streams with low level API (i.e. accessing `MongoCollection`)
